### ISSUE TITLE
Piano prefab is missing

### ISSUE THREAD

**Issue by AlexeyNovik** [eddiman/VirtualPiano#1]
By the moment the project does not contain piano prefab, so there is quite a big amount of broken objects. Could you please fix this issue or guide to the asset you were using?

**Comment by eddiman** [comment]
Hmm, strange. I cloned and set up the project on a different computer, and the piano prefab loads perfectly fine. The piano prefab is built upon the .blend file, found in the "Model"-folder. Another issue could maybe be that the VRTK framework didn't load properly, as the functionality of tangents are built using that framework? You can find it in the pacakage manager.

Edit from the far future: 
Its stored in . blend file, som you need Blender installed in order for Unity to use its built-in .blend to .fbx converter.

**Comment by yujie-tao** [comment]
I have the same issue of missing the piano prefab. Have we found the ways to solve it?
